default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: brian
  password: 
  port: 5432
  pool: 5

development:
  <<: *default
  database: zerocoin_project_development

test:
  <<: *default
  database: zerocoin_project_test


